#!/usr/bin/env bash
CWD=`pwd`
BAK_DIR=~/dotfiles.backup

if [ -d "$BAK_DIR" ]; then
	echo -n "The directory '$BAK_DIR' exists. Press ENTER to delete the directory and continue or Ctrl+C to cancel."
	read
	rm -rf ${BAK_DIR}
fi
mkdir ${BAK_DIR}

## Setup vim
# Backup the existing vim conf
mv ~/.vimrc ${BAK_DIR}/vimrc
mv ~/.vim ${BAK_DIR}/vim
# Create symlinks to the new files
ln -s ${CWD}/vim/vimrc ~/.vimrc
# Create the temporary directories required by the vimrc
mkdir -p ~/.vim/tmp/undo
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
# Install the vim plugins using vundle
vim +PluginInstall +qall

## Install .profile and .aliases
mv ~/.profile ${BAK_DIR}/profile
ln -s ${CWD}/shell/profile ~/.profile
[ -f ~/.aliases ] && mv ~/.aliases ${BAK_DIR}/aliases
ln -s ${CWD}/shell/aliases ~/.aliases

## Install bash conf
ZSH_DIR=~/.zsh

mkdir -p ${BAK_DIR}/zsh/
mv ~/.zshrc ${BAK_DIR}/zsh/zshrc
mv ~/.zprofile ${BAK_DIR}/zsh/zprofile
mv $ZSH_DIR ${BAK_DIR}/zsh/zsh

mkdir -p $ZSH_DIR

ln -s ${CWD}/shell/zsh/zshrc ~/.zshrc
ln -s ${CWD}/shell/zsh/zprofile ~/.zprofile

for config_file in ${CWD}/shell/zsh/*.zsh; do
    ln -s $config_file ${ZSH_DIR}/`basename $config_file`
done

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_DIR/syntax-highlighting

## Install tmux conf
mv ~/.tmux.conf ${BAK_DIR}/tmux.conf
ln -s ${CWD}/shell/tmux.conf ~/.tmux.conf

## Install screen conf
mv ~/.screenrc ${BAK_DIR}/screenrc
ln -s ${CWD}/screen/screenrc ~/.screenrc

## neovim configuration
mv  ~/.config/nvim ${BAK_DIR}/nvim 2>/dev/null || true # Silently move without throwing error if the file doesnt exist
ln -s ${CWD}/nvim ~/.config/nvim
