#!/usr/bin/env bash
CWD=`pwd`

# Setup vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
ln -s ${CWD}/vim/vimrc ~/.vimrc
# Install the vim plugins using vundle
vim +PluginInstall +qall
